"""
Scaffold Tool — generate new CLI tool skeletons from template.

The model can use this to create project-specific CLI tools
that inherit the security framework and structured output patterns.
"""

import re
from pathlib import Path
from typing import Any

from nexus.cli.utils import (
    OutputFormat, Status, emit, make_result,
)


_TOOL_TEMPLATE = '''\
"""
{description}

Auto-generated by bs-cli scaffold. Inherits security.py validators.
"""

# SECURITY: This tool must:
# - Never use shell=True in subprocess calls
# - Never use eval() or exec()
# - Validate all path inputs via security.validate_path()
# - Validate all URL inputs via security.validate_url()
# - Emit structured output via utils.emit()

from pathlib import Path
from typing import Any

from nexus.cli.utils import (
    OutputFormat, Status, emit, make_result,
)
from nexus.cli.security import validate_path, validate_url


def run_{fn_name}(
    output_format: str = "json",
    project_dir: str = ".",
    **kwargs,
) -> None:
    """Run the {name} tool."""
    fmt = OutputFormat(output_format)
    proj_path = Path(project_dir).resolve()

    # TODO: Implement tool logic here

    result = make_result("{name}", Status.INFO, "{name} executed successfully")
    result["details"] = {{
        "project_dir": str(proj_path),
    }}

    emit(result, fmt)
'''


def _sanitize_name(name: str) -> str:
    """Sanitize tool name to valid Python identifier."""
    # Only allow alphanumeric and hyphens
    clean = re.sub(r"[^a-zA-Z0-9\-]", "", name)
    if not clean:
        raise ValueError(f"Invalid tool name: '{name}'")
    return clean.lower()


def _name_to_fn(name: str) -> str:
    """Convert hyphenated name to Python function name."""
    return name.replace("-", "_")


def run_scaffold(
    name: str,
    description: str = "",
    output_format: str = "json",
) -> None:
    """Generate a new CLI tool skeleton."""
    fmt = OutputFormat(output_format)

    try:
        clean_name = _sanitize_name(name)
    except ValueError as e:
        result = make_result("scaffold", Status.FAIL, str(e))
        emit(result, fmt)
        return

    fn_name = _name_to_fn(clean_name)

    if not description:
        description = f"{clean_name} — custom CLI tool (auto-scaffolded)"

    # Generate the tool file
    tools_dir = Path(__file__).parent
    tool_path = tools_dir / f"{fn_name}.py"

    if tool_path.exists():
        result = make_result(
            "scaffold", Status.FAIL,
            f"Tool already exists: {tool_path.name}. Choose a different name or edit the existing file.",
        )
        emit(result, fmt)
        return

    content = _TOOL_TEMPLATE.format(
        name=clean_name,
        fn_name=fn_name,
        description=description,
    )

    tool_path.write_text(content, encoding="utf-8")

    # Generate registration snippet for bs_cli.py
    registration_snippet = f"""
@cli.command("{clean_name}")
@click.option("--format", "output_format", type=click.Choice(["json", "human", "yaml"]), default="json")
@click.option("--project-dir", default=".", help="Project directory.")
@click.pass_context
def {fn_name}_cmd(ctx, output_format, project_dir):
    \"\"\"{description}\"\"\"
    from nexus.cli.tools.{fn_name} import run_{fn_name}
    run_{fn_name}(output_format=output_format, project_dir=project_dir)
"""

    result = make_result("scaffold", Status.PASS, f"Tool '{clean_name}' scaffolded successfully")
    result["details"] = {
        "tool_file": str(tool_path),
        "tool_name": clean_name,
        "function_name": f"run_{fn_name}",
    }
    result["registration"] = {
        "message": "Add this snippet to bs_cli.py to register the tool:",
        "snippet": registration_snippet.strip(),
    }
    result["next_steps"] = [
        f"1. Edit {tool_path.name} to implement your tool logic",
        "2. Add the registration snippet to bs_cli.py",
        f"3. Test: python bootstrap/cli/bs_cli.py {clean_name} --format human",
    ]

    emit(result, fmt)
