#!/usr/bin/env python3
"""Ensure WORKSPACE_MCP_SIGNING_KEY is set in .env (idempotent).

The workspace-mcp container needs a stable Fernet-derivable signing key for
its OAuth-token persistence (FASTMCP_SERVER_AUTH_GOOGLE_JWT_SIGNING_KEY).
If unset, the image falls back to deriving one from GOOGLE_OAUTH_CLIENT_SECRET
— stable until the secret is rotated, at which point every persisted token
becomes unreadable.

This helper:
  - Reads .env and looks for `WORKSPACE_MCP_SIGNING_KEY=<value>`.
  - If missing or empty, generates a 64-char hex key via `secrets.token_hex(32)`
    and appends it (preserving every other line).
  - If present and non-empty, prints the existing key's first 8 chars + length
    and exits 0 — never overwrites.

Run after copying .env.example → .env, before `docker compose up`. Safe to
re-run; idempotent.
"""

from __future__ import annotations

import secrets
import sys
from pathlib import Path

KEY_NAME = "WORKSPACE_MCP_SIGNING_KEY"
ENV_PATH = Path(__file__).resolve().parents[1] / ".env"


def main() -> int:
    if not ENV_PATH.exists():
        print(
            f"ERROR: {ENV_PATH} not found. Copy .env.example to .env first.",
            file=sys.stderr,
        )
        return 1

    lines = ENV_PATH.read_text(encoding="utf-8").splitlines()

    existing_idx: int | None = None
    existing_value = ""
    for idx, line in enumerate(lines):
        stripped = line.lstrip()
        if stripped.startswith("#"):
            continue
        if stripped.startswith(f"{KEY_NAME}="):
            existing_idx = idx
            existing_value = stripped.split("=", 1)[1].strip()
            break

    if existing_idx is not None and existing_value:
        print(
            f"{KEY_NAME} already set (prefix={existing_value[:8]}..., "
            f"length={len(existing_value)}). No changes."
        )
        return 0

    new_key = secrets.token_hex(32)  # 64 hex chars; sufficient entropy

    if existing_idx is not None:
        # Empty assignment present — fill it in place to keep position/comments.
        lines[existing_idx] = f"{KEY_NAME}={new_key}"
    else:
        # No assignment line at all — append with a small explanatory header.
        if lines and lines[-1] != "":
            lines.append("")
        lines.append("# Auto-generated by scripts/ensure_workspace_mcp_key.py.")
        lines.append("# DO NOT rotate without re-running /connect google for all users.")
        lines.append(f"{KEY_NAME}={new_key}")

    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(
        f"Generated {KEY_NAME} (prefix={new_key[:8]}..., length={len(new_key)}). "
        f"Wrote to {ENV_PATH}."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
