"""Seed data for the openai_models table.

Each dict maps directly to an OpenAIModel row.  Pricing is per 1M tokens
(or per minute / per 1M characters where noted) sourced from OpenAI's
published rates as of 2026-03.
"""

_DOCS = "https://developers.openai.com/api/docs/models"
_CHAT = "/v1/chat/completions"
_IMG = "/v1/images/generations"
_AUDIO_SPEECH = "/v1/audio/speech"
_AUDIO_TRANSCRIPTION = "/v1/audio/transcriptions"
_EMBEDDINGS = "/v1/embeddings"
_MODERATIONS = "/v1/moderations"
_REALTIME = "/v1/realtime/sessions"
_RESPONSES = "/v1/responses"

_REASONING = ["none", "low", "medium", "high", "xhigh"]


def _doc(model_id: str) -> str:
    return f"{_DOCS}/{model_id}"


OPENAI_MODELS: list[dict] = [
    # ── GPT-5.4 family (flagship) ──────────────────────────────────────
    {
        "model_id": "gpt-5.4",
        "display_name": "GPT-5.4",
        "family": "gpt-5.4",
        "category": "reasoning",
        "description": "Best intelligence at scale for agentic, coding, and professional workflows",
        "strengths": ["agentic", "coding", "long-context", "reasoning", "professional"],
        "use_cases": ["orchestration", "complex-analysis", "multi-step-tasks"],
        "context_window": 272000,
        "max_output_tokens": 16384,
        "reasoning_effort_levels": _REASONING,
        "pricing_input": 2.50,
        "pricing_cached_input": 1.25,
        "pricing_output": 15.00,
        "pricing_unit": "per_1m_tokens",
        "pricing_notes": "Input doubles to $5.00 above 272K context",
        "api_docs_url": _doc("gpt-5.4"),
        "api_endpoint": _CHAT,
        "is_enabled": True,
        "atlas_role": "orchestrator",
    },
    {
        "model_id": "gpt-5.4-pro",
        "display_name": "GPT-5.4 Pro",
        "family": "gpt-5.4",
        "category": "reasoning",
        "description": "Smarter, more precise responses with premium deep-horizon reasoning",
        "strengths": ["deep-reasoning", "precision", "complex-analysis"],
        "use_cases": ["high-stakes-analysis", "enterprise-reasoning"],
        "context_window": 272000,
        "max_output_tokens": 16384,
        "reasoning_effort_levels": _REASONING,
        "pricing_input": 30.00,
        "pricing_cached_input": None,
        "pricing_output": 180.00,
        "pricing_unit": "per_1m_tokens",
        "pricing_notes": "Premium reasoning tier; specialized hardware",
        "api_docs_url": _doc("gpt-5.4-pro"),
        "api_endpoint": _CHAT,
        "is_enabled": False,
    },
    {
        "model_id": "gpt-5.4-mini",
        "display_name": "GPT-5.4 Mini",
        "family": "gpt-5.4",
        "category": "reasoning",
        "description": "Strongest mini model for coding, computer use, and subagent workflows",
        "strengths": ["coding", "computer-use", "subagents", "tool-calling"],
        "use_cases": ["coding", "debugging", "general-assistant", "subagent-executor"],
        "context_window": 400000,
        "max_output_tokens": 16384,
        "reasoning_effort_levels": _REASONING,
        "pricing_input": 0.75,
        "pricing_cached_input": 0.375,
        "pricing_output": 4.50,
        "pricing_unit": "per_1m_tokens",
        "api_docs_url": _doc("gpt-5.4-mini"),
        "api_endpoint": _CHAT,
        "is_enabled": True,
        "atlas_role": "coding",
    },
    {
        "model_id": "gpt-5.4-nano",
        "display_name": "GPT-5.4 Nano",
        "family": "gpt-5.4",
        "category": "reasoning",
        "description": "Cheapest GPT-5.4-class model for simple, high-volume tasks",
        "strengths": ["fast", "cheap", "classification", "routing"],
        "use_cases": ["routing", "classification", "guardrails", "scoring"],
        "context_window": 272000,
        "max_output_tokens": 16384,
        "reasoning_effort_levels": _REASONING,
        "pricing_input": 0.20,
        "pricing_cached_input": 0.10,
        "pricing_output": 1.25,
        "pricing_unit": "per_1m_tokens",
        "api_docs_url": _doc("gpt-5.4-nano"),
        "api_endpoint": _CHAT,
        "is_enabled": True,
        "atlas_role": "fast",
    },

    # ── GPT-5 family (previous gen) ────────────────────────────────────
    {
        "model_id": "gpt-5",
        "display_name": "GPT-5",
        "family": "gpt-5",
        "category": "reasoning",
        "description": "Previous-gen intelligent reasoning model",
        "strengths": ["reasoning", "general-purpose"],
        "use_cases": ["general-assistant", "analysis"],
        "context_window": 128000,
        "max_output_tokens": 16384,
        "reasoning_effort_levels": _REASONING,
        "pricing_input": 1.25,
        "pricing_cached_input": 0.125,
        "pricing_output": 10.00,
        "pricing_unit": "per_1m_tokens",
        "api_docs_url": _doc("gpt-5"),
        "api_endpoint": _CHAT,
        "notes": "Succeeded by gpt-5.4",
    },
    {
        "model_id": "gpt-5-pro",
        "display_name": "GPT-5 Pro",
        "family": "gpt-5",
        "category": "reasoning",
        "description": "Smarter GPT-5 responses with deeper reasoning",
        "strengths": ["deep-reasoning", "precision"],
        "use_cases": ["high-stakes-analysis"],
        "context_window": 128000,
        "max_output_tokens": 16384,
        "reasoning_effort_levels": _REASONING,
        "pricing_input": 15.00,
        "pricing_cached_input": None,
        "pricing_output": 120.00,
        "pricing_unit": "per_1m_tokens",
        "api_docs_url": _doc("gpt-5-pro"),
        "api_endpoint": _CHAT,
        "notes": "Succeeded by gpt-5.4-pro",
    },
    {
        "model_id": "gpt-5-mini",
        "display_name": "GPT-5 Mini",
        "family": "gpt-5",
        "category": "reasoning",
        "description": "Near-frontier model for cost-sensitive workloads",
        "strengths": ["balanced", "cost-effective"],
        "use_cases": ["general-assistant", "coding"],
        "context_window": 128000,
        "max_output_tokens": 16384,
        "reasoning_effort_levels": _REASONING,
        "pricing_input": 0.25,
        "pricing_cached_input": 0.025,
        "pricing_output": 2.00,
        "pricing_unit": "per_1m_tokens",
        "api_docs_url": _doc("gpt-5-mini"),
        "api_endpoint": _CHAT,
        "notes": "Succeeded by gpt-5.4-mini",
    },
    {
        "model_id": "gpt-5-nano",
        "display_name": "GPT-5 Nano",
        "family": "gpt-5",
        "category": "reasoning",
        "description": "Fastest and cheapest GPT-5 variant",
        "strengths": ["fast", "cheap"],
        "use_cases": ["routing", "classification"],
        "context_window": 128000,
        "max_output_tokens": 16384,
        "reasoning_effort_levels": _REASONING,
        "pricing_input": 0.05,
        "pricing_cached_input": 0.005,
        "pricing_output": 0.40,
        "pricing_unit": "per_1m_tokens",
        "api_docs_url": _doc("gpt-5-nano"),
        "api_endpoint": _CHAT,
        "notes": "Succeeded by gpt-5.4-nano",
    },
    {
        "model_id": "gpt-5.1",
        "display_name": "GPT-5.1",
        "family": "gpt-5",
        "category": "reasoning",
        "description": "Best for coding and agentic tasks with configurable reasoning",
        "strengths": ["coding", "agentic", "reasoning"],
        "use_cases": ["coding", "agentic-workflows"],
        "context_window": 128000,
        "max_output_tokens": 16384,
        "reasoning_effort_levels": _REASONING,
        "pricing_input": 1.25,
        "pricing_cached_input": 0.125,
        "pricing_output": 10.00,
        "pricing_unit": "per_1m_tokens",
        "api_docs_url": _doc("gpt-5.1"),
        "api_endpoint": _CHAT,
    },
    {
        "model_id": "gpt-5.2",
        "display_name": "GPT-5.2",
        "family": "gpt-5",
        "category": "reasoning",
        "description": "Previous frontier model for professional work",
        "strengths": ["professional", "reasoning", "coding"],
        "use_cases": ["professional-workflows", "analysis"],
        "context_window": 128000,
        "max_output_tokens": 16384,
        "reasoning_effort_levels": _REASONING,
        "pricing_input": 1.75,
        "pricing_cached_input": 0.175,
        "pricing_output": 14.00,
        "pricing_unit": "per_1m_tokens",
        "api_docs_url": _doc("gpt-5.2"),
        "api_endpoint": _CHAT,
        "notes": "Succeeded by gpt-5.4",
    },
    {
        "model_id": "gpt-5.2-pro",
        "display_name": "GPT-5.2 Pro",
        "family": "gpt-5",
        "category": "reasoning",
        "description": "Previous pro-tier model with deep reasoning",
        "strengths": ["deep-reasoning", "precision"],
        "use_cases": ["high-stakes-analysis"],
        "context_window": 128000,
        "max_output_tokens": 16384,
        "reasoning_effort_levels": _REASONING,
        "pricing_input": 21.00,
        "pricing_cached_input": None,
        "pricing_output": 168.00,
        "pricing_unit": "per_1m_tokens",
        "api_docs_url": _doc("gpt-5.2-pro"),
        "api_endpoint": _CHAT,
        "notes": "Succeeded by gpt-5.4-pro",
    },

    # ── GPT-4.1 family (non-reasoning, previous Atlas defaults) ────────
    {
        "model_id": "gpt-4.1",
        "display_name": "GPT-4.1",
        "family": "gpt-4.1",
        "category": "general",
        "description": "Smartest non-reasoning model with 1M context window",
        "strengths": ["long-context", "instruction-following", "general-purpose"],
        "use_cases": ["general-assistant", "document-analysis"],
        "context_window": 1000000,
        "max_output_tokens": 32768,
        "reasoning_effort_levels": None,
        "pricing_input": 2.00,
        "pricing_cached_input": 0.50,
        "pricing_output": 8.00,
        "pricing_unit": "per_1m_tokens",
        "api_docs_url": _doc("gpt-4.1"),
        "api_endpoint": _CHAT,
        "notes": "Previous Atlas orchestrator default",
    },
    {
        "model_id": "gpt-4.1-mini",
        "display_name": "GPT-4.1 Mini",
        "family": "gpt-4.1",
        "category": "general",
        "description": "Smaller, faster GPT-4.1 for cost-sensitive tasks",
        "strengths": ["fast", "cost-effective", "balanced"],
        "use_cases": ["general-assistant", "coding"],
        "context_window": 1000000,
        "max_output_tokens": 32768,
        "reasoning_effort_levels": None,
        "pricing_input": 0.40,
        "pricing_cached_input": 0.10,
        "pricing_output": 1.60,
        "pricing_unit": "per_1m_tokens",
        "api_docs_url": _doc("gpt-4.1-mini"),
        "api_endpoint": _CHAT,
        "notes": "Previous Atlas code_gen default",
    },
    {
        "model_id": "gpt-4.1-nano",
        "display_name": "GPT-4.1 Nano",
        "family": "gpt-4.1",
        "category": "general",
        "description": "Fastest, most cost-efficient GPT-4.1",
        "strengths": ["fast", "cheap", "classification"],
        "use_cases": ["routing", "classification", "guardrails"],
        "context_window": 1000000,
        "max_output_tokens": 32768,
        "reasoning_effort_levels": None,
        "pricing_input": 0.10,
        "pricing_cached_input": 0.025,
        "pricing_output": 0.40,
        "pricing_unit": "per_1m_tokens",
        "api_docs_url": _doc("gpt-4.1-nano"),
        "api_endpoint": _CHAT,
        "notes": "Previous Atlas fast default",
    },

    # ── Codex family (agentic coding) ──────────────────────────────────
    {
        "model_id": "gpt-5.3-codex",
        "display_name": "GPT-5.3 Codex",
        "family": "codex",
        "category": "coding",
        "description": "Most advanced agentic coding model; SWE-Bench Pro SOTA",
        "strengths": ["coding", "debugging", "terminal", "computer-use", "agentic"],
        "use_cases": ["self-healing", "code-generation", "debugging", "deployment"],
        "context_window": 400000,
        "max_output_tokens": 128000,
        "reasoning_effort_levels": None,
        "pricing_input": 1.75,
        "pricing_cached_input": None,
        "pricing_output": 14.00,
        "pricing_unit": "per_1m_tokens",
        "pricing_notes": "Optimized for long-running agentic coding workflows",
        "api_docs_url": _doc("gpt-5.3-codex"),
        "api_endpoint": _RESPONSES,
        "atlas_role": "repair",
    },
    {
        "model_id": "gpt-5.2-codex",
        "display_name": "GPT-5.2 Codex",
        "family": "codex",
        "category": "coding",
        "description": "Most intelligent coding model for long-horizon agentic tasks",
        "strengths": ["coding", "long-horizon", "agentic"],
        "use_cases": ["code-generation", "debugging"],
        "context_window": 400000,
        "max_output_tokens": 128000,
        "reasoning_effort_levels": None,
        "pricing_input": 1.75,
        "pricing_cached_input": None,
        "pricing_output": 14.00,
        "pricing_unit": "per_1m_tokens",
        "api_docs_url": _doc("gpt-5.2-codex"),
        "api_endpoint": _RESPONSES,
    },
    {
        "model_id": "gpt-5.1-codex",
        "display_name": "GPT-5.1 Codex",
        "family": "codex",
        "category": "coding",
        "description": "GPT-5.1 optimized for agentic coding",
        "strengths": ["coding", "agentic"],
        "use_cases": ["code-generation"],
        "context_window": 400000,
        "max_output_tokens": 128000,
        "reasoning_effort_levels": None,
        "pricing_input": 1.25,
        "pricing_cached_input": None,
        "pricing_output": 10.00,
        "pricing_unit": "per_1m_tokens",
        "api_docs_url": _doc("gpt-5.1-codex"),
        "api_endpoint": _RESPONSES,
    },
    {
        "model_id": "gpt-5.1-codex-max",
        "display_name": "GPT-5.1 Codex Max",
        "family": "codex",
        "category": "coding",
        "description": "Long-running agentic coding tasks with extended compute",
        "strengths": ["coding", "long-running", "agentic"],
        "use_cases": ["complex-refactoring", "large-codebase"],
        "context_window": 400000,
        "max_output_tokens": 128000,
        "reasoning_effort_levels": None,
        "pricing_input": 1.25,
        "pricing_cached_input": None,
        "pricing_output": 10.00,
        "pricing_unit": "per_1m_tokens",
        "api_docs_url": _doc("gpt-5.1-codex-max"),
        "api_endpoint": _RESPONSES,
    },
    {
        "model_id": "gpt-5.1-codex-mini",
        "display_name": "GPT-5.1 Codex Mini",
        "family": "codex",
        "category": "coding",
        "description": "Smaller, cost-effective coding model",
        "strengths": ["coding", "cost-effective"],
        "use_cases": ["simple-coding", "code-review"],
        "context_window": 400000,
        "max_output_tokens": 128000,
        "reasoning_effort_levels": None,
        "pricing_input": 0.25,
        "pricing_cached_input": None,
        "pricing_output": 2.00,
        "pricing_unit": "per_1m_tokens",
        "api_docs_url": _doc("gpt-5.1-codex-mini"),
        "api_endpoint": _RESPONSES,
    },
    {
        "model_id": "gpt-5-codex",
        "display_name": "GPT-5 Codex",
        "family": "codex",
        "category": "coding",
        "description": "GPT-5 optimized for agentic coding",
        "strengths": ["coding", "agentic"],
        "use_cases": ["code-generation"],
        "context_window": 400000,
        "max_output_tokens": 128000,
        "reasoning_effort_levels": None,
        "pricing_input": 1.25,
        "pricing_cached_input": None,
        "pricing_output": 10.00,
        "pricing_unit": "per_1m_tokens",
        "api_docs_url": _doc("gpt-5-codex"),
        "api_endpoint": _RESPONSES,
    },

    # ── Image generation ───────────────────────────────────────────────
    {
        "model_id": "gpt-image-1",
        "display_name": "GPT Image 1",
        "family": "image",
        "category": "image",
        "description": "State-of-the-art image generation and editing",
        "strengths": ["image-generation", "image-editing", "multimodal"],
        "use_cases": ["image-creation", "design"],
        "context_window": None,
        "max_output_tokens": None,
        "reasoning_effort_levels": None,
        "pricing_input": 10.00,
        "pricing_cached_input": 2.50,
        "pricing_output": 40.00,
        "pricing_unit": "per_1m_tokens",
        "pricing_notes": "Per-image: $0.011 (low) to $0.25 (high) for 1024x1024",
        "api_docs_url": _doc("gpt-image-1"),
        "api_endpoint": _IMG,
        "atlas_role": "image_gen",
    },
    {
        "model_id": "gpt-image-1-mini",
        "display_name": "GPT Image 1 Mini",
        "family": "image",
        "category": "image",
        "description": "Cost-efficient image generation",
        "strengths": ["image-generation", "cost-effective"],
        "use_cases": ["batch-image-creation"],
        "context_window": None,
        "max_output_tokens": None,
        "reasoning_effort_levels": None,
        "pricing_input": 2.50,
        "pricing_cached_input": 0.25,
        "pricing_output": 8.00,
        "pricing_unit": "per_1m_tokens",
        "pricing_notes": "Per-image: $0.005 (low) to $0.052 (high) for 1024x1024",
        "api_docs_url": _doc("gpt-image-1-mini"),
        "api_endpoint": _IMG,
        "atlas_role": "image_gen",
    },

    # ── Video generation ───────────────────────────────────────────────
    {
        "model_id": "sora-2",
        "display_name": "Sora 2",
        "family": "video",
        "category": "video",
        "description": "Flagship video generation with synced audio",
        "strengths": ["video-generation", "audio-sync"],
        "use_cases": ["video-creation"],
        "context_window": None,
        "max_output_tokens": None,
        "reasoning_effort_levels": None,
        "pricing_unit": "per_second",
        "pricing_notes": "Per-second pricing; varies by resolution",
        "api_docs_url": _doc("sora-2"),
        "api_endpoint": "/v1/video/generations",
        "atlas_role": "video_gen",
    },
    {
        "model_id": "sora-2-pro",
        "display_name": "Sora 2 Pro",
        "family": "video",
        "category": "video",
        "description": "Most advanced synced-audio video generation",
        "strengths": ["video-generation", "premium-quality"],
        "use_cases": ["professional-video"],
        "context_window": None,
        "max_output_tokens": None,
        "reasoning_effort_levels": None,
        "pricing_unit": "per_second",
        "pricing_notes": "Premium per-second pricing",
        "api_docs_url": _doc("sora-2-pro"),
        "api_endpoint": "/v1/video/generations",
        "atlas_role": "video_gen",
    },

    # ── Audio / Realtime ───────────────────────────────────────────────
    {
        "model_id": "gpt-realtime",
        "display_name": "GPT Realtime",
        "family": "realtime",
        "category": "realtime",
        "description": "Realtime text and audio I/O for voice applications",
        "strengths": ["voice", "realtime", "low-latency"],
        "use_cases": ["voice-assistant", "phone-support"],
        "context_window": 128000,
        "max_output_tokens": 4096,
        "reasoning_effort_levels": None,
        "pricing_input": 4.00,
        "pricing_cached_input": 0.40,
        "pricing_output": 16.00,
        "pricing_unit": "per_1m_tokens",
        "pricing_notes": "Text tokens; audio: $32.00 in / $64.00 out per 1M tokens",
        "api_docs_url": _doc("gpt-realtime"),
        "api_endpoint": _REALTIME,
        "atlas_role": "realtime",
    },
    {
        "model_id": "gpt-realtime-mini",
        "display_name": "GPT Realtime Mini",
        "family": "realtime",
        "category": "realtime",
        "description": "Cost-efficient realtime voice model",
        "strengths": ["voice", "realtime", "cost-effective"],
        "use_cases": ["voice-assistant"],
        "context_window": 128000,
        "max_output_tokens": 4096,
        "reasoning_effort_levels": None,
        "pricing_input": 0.60,
        "pricing_cached_input": 0.06,
        "pricing_output": 2.40,
        "pricing_unit": "per_1m_tokens",
        "pricing_notes": "Text tokens; audio: $10.00 in / $20.00 out per 1M tokens",
        "api_docs_url": _doc("gpt-realtime-mini"),
        "api_endpoint": _REALTIME,
        "atlas_role": "realtime",
    },
    {
        "model_id": "gpt-audio",
        "display_name": "GPT Audio",
        "family": "audio",
        "category": "audio",
        "description": "Audio I/O via Chat Completions API",
        "strengths": ["audio", "speech"],
        "use_cases": ["audio-processing", "voice-interaction"],
        "context_window": 128000,
        "max_output_tokens": 16384,
        "reasoning_effort_levels": None,
        "pricing_input": 32.00,
        "pricing_output": 64.00,
        "pricing_unit": "per_1m_tokens",
        "pricing_notes": "Audio token pricing",
        "api_docs_url": _doc("gpt-audio"),
        "api_endpoint": _CHAT,
    },
    {
        "model_id": "gpt-audio-mini",
        "display_name": "GPT Audio Mini",
        "family": "audio",
        "category": "audio",
        "description": "Cost-efficient audio model",
        "strengths": ["audio", "cost-effective"],
        "use_cases": ["audio-processing"],
        "context_window": 128000,
        "max_output_tokens": 16384,
        "reasoning_effort_levels": None,
        "pricing_input": 10.00,
        "pricing_output": 20.00,
        "pricing_unit": "per_1m_tokens",
        "pricing_notes": "Audio token pricing",
        "api_docs_url": _doc("gpt-audio-mini"),
        "api_endpoint": _CHAT,
    },

    # ── Speech-to-Text ─────────────────────────────────────────────────
    {
        "model_id": "gpt-4o-transcribe",
        "display_name": "GPT-4o Transcribe",
        "family": "audio",
        "category": "stt",
        "description": "Speech-to-text powered by GPT-4o",
        "strengths": ["transcription", "accuracy"],
        "use_cases": ["voice-transcription", "meeting-notes"],
        "context_window": None,
        "max_output_tokens": None,
        "reasoning_effort_levels": None,
        "pricing_input": 0.006,
        "pricing_output": None,
        "pricing_unit": "per_minute",
        "api_docs_url": _doc("gpt-4o-transcribe"),
        "api_endpoint": _AUDIO_TRANSCRIPTION,
        "atlas_role": "stt",
    },
    {
        "model_id": "gpt-4o-mini-transcribe",
        "display_name": "GPT-4o Mini Transcribe",
        "family": "audio",
        "category": "stt",
        "description": "Cost-efficient speech-to-text powered by GPT-4o Mini",
        "strengths": ["transcription", "cost-effective"],
        "use_cases": ["voice-transcription"],
        "context_window": None,
        "max_output_tokens": None,
        "reasoning_effort_levels": None,
        "pricing_input": 0.003,
        "pricing_output": None,
        "pricing_unit": "per_minute",
        "api_docs_url": _doc("gpt-4o-mini-transcribe"),
        "api_endpoint": _AUDIO_TRANSCRIPTION,
        "atlas_role": "stt",
    },
    {
        "model_id": "gpt-4o-transcribe-diarize",
        "display_name": "GPT-4o Transcribe + Diarize",
        "family": "audio",
        "category": "stt",
        "description": "Transcription with speaker identification",
        "strengths": ["transcription", "speaker-id"],
        "use_cases": ["meeting-transcription"],
        "context_window": None,
        "max_output_tokens": None,
        "reasoning_effort_levels": None,
        "pricing_input": 0.006,
        "pricing_output": None,
        "pricing_unit": "per_minute",
        "api_docs_url": _doc("gpt-4o-transcribe-diarize"),
        "api_endpoint": _AUDIO_TRANSCRIPTION,
        "atlas_role": "stt",
    },
    {
        "model_id": "whisper-1",
        "display_name": "Whisper",
        "family": "audio",
        "category": "stt",
        "description": "General-purpose speech recognition model",
        "strengths": ["transcription", "multilingual"],
        "use_cases": ["voice-transcription"],
        "context_window": None,
        "max_output_tokens": None,
        "reasoning_effort_levels": None,
        "pricing_input": 0.006,
        "pricing_output": None,
        "pricing_unit": "per_minute",
        "api_docs_url": _doc("whisper-1"),
        "api_endpoint": _AUDIO_TRANSCRIPTION,
        "atlas_role": "stt",
    },

    # ── Text-to-Speech ─────────────────────────────────────────────────
    {
        "model_id": "gpt-4o-mini-tts",
        "display_name": "GPT-4o Mini TTS",
        "family": "audio",
        "category": "tts",
        "description": "Text-to-speech powered by GPT-4o Mini",
        "strengths": ["tts", "natural-voice"],
        "use_cases": ["voice-output", "accessibility"],
        "context_window": None,
        "max_output_tokens": None,
        "reasoning_effort_levels": None,
        "pricing_input": 0.015,
        "pricing_output": None,
        "pricing_unit": "per_minute",
        "api_docs_url": _doc("gpt-4o-mini-tts"),
        "api_endpoint": _AUDIO_SPEECH,
        "atlas_role": "tts",
    },
    {
        "model_id": "tts-1",
        "display_name": "TTS-1",
        "family": "audio",
        "category": "tts",
        "description": "Text-to-speech optimized for speed",
        "strengths": ["tts", "fast"],
        "use_cases": ["voice-output"],
        "context_window": None,
        "max_output_tokens": None,
        "reasoning_effort_levels": None,
        "pricing_input": 15.00,
        "pricing_output": None,
        "pricing_unit": "per_1m_chars",
        "api_docs_url": _doc("tts-1"),
        "api_endpoint": _AUDIO_SPEECH,
        "atlas_role": "tts",
    },
    {
        "model_id": "tts-1-hd",
        "display_name": "TTS-1 HD",
        "family": "audio",
        "category": "tts",
        "description": "Text-to-speech optimized for quality",
        "strengths": ["tts", "high-quality"],
        "use_cases": ["premium-voice-output"],
        "context_window": None,
        "max_output_tokens": None,
        "reasoning_effort_levels": None,
        "pricing_input": 30.00,
        "pricing_output": None,
        "pricing_unit": "per_1m_chars",
        "api_docs_url": _doc("tts-1-hd"),
        "api_endpoint": _AUDIO_SPEECH,
        "atlas_role": "tts",
    },

    # ── Embeddings ─────────────────────────────────────────────────────
    {
        "model_id": "text-embedding-3-large",
        "display_name": "Text Embedding 3 Large",
        "family": "embedding",
        "category": "embedding",
        "description": "Most capable embedding model for search and classification",
        "strengths": ["embeddings", "search", "classification"],
        "use_cases": ["semantic-search", "RAG", "clustering"],
        "context_window": 8191,
        "max_output_tokens": None,
        "reasoning_effort_levels": None,
        "pricing_input": 0.13,
        "pricing_output": None,
        "pricing_unit": "per_1m_tokens",
        "pricing_notes": "Batch: $0.065",
        "api_docs_url": _doc("text-embedding-3-large"),
        "api_endpoint": _EMBEDDINGS,
        "atlas_role": "embedding",
    },
    {
        "model_id": "text-embedding-3-small",
        "display_name": "Text Embedding 3 Small",
        "family": "embedding",
        "category": "embedding",
        "description": "Small, efficient embedding model",
        "strengths": ["embeddings", "cost-effective"],
        "use_cases": ["semantic-search", "classification"],
        "context_window": 8191,
        "max_output_tokens": None,
        "reasoning_effort_levels": None,
        "pricing_input": 0.02,
        "pricing_output": None,
        "pricing_unit": "per_1m_tokens",
        "pricing_notes": "Batch: $0.01",
        "api_docs_url": _doc("text-embedding-3-small"),
        "api_endpoint": _EMBEDDINGS,
        "atlas_role": "embedding",
    },
    {
        "model_id": "text-embedding-ada-002",
        "display_name": "Text Embedding Ada 002",
        "family": "embedding",
        "category": "embedding",
        "description": "Legacy embedding model",
        "strengths": ["embeddings"],
        "use_cases": ["semantic-search"],
        "context_window": 8191,
        "max_output_tokens": None,
        "reasoning_effort_levels": None,
        "pricing_input": 0.10,
        "pricing_output": None,
        "pricing_unit": "per_1m_tokens",
        "pricing_notes": "Batch: $0.05",
        "api_docs_url": _doc("text-embedding-ada-002"),
        "api_endpoint": _EMBEDDINGS,
        "is_deprecated": True,
        "notes": "Succeeded by text-embedding-3-small/large",
    },

    # ── Moderation ─────────────────────────────────────────────────────
    {
        "model_id": "omni-moderation-latest",
        "display_name": "Omni Moderation",
        "family": "moderation",
        "category": "moderation",
        "description": "Harmful content detection for text and images",
        "strengths": ["content-moderation", "safety"],
        "use_cases": ["content-filtering", "safety-checks"],
        "context_window": None,
        "max_output_tokens": None,
        "reasoning_effort_levels": None,
        "pricing_unit": "per_1m_tokens",
        "pricing_notes": "Free for moderation endpoint",
        "api_docs_url": _doc("omni-moderation-latest"),
        "api_endpoint": _MODERATIONS,
        "atlas_role": "moderation",
    },

    # ── Research ───────────────────────────────────────────────────────
    {
        "model_id": "o3-deep-research",
        "display_name": "o3 Deep Research",
        "family": "research",
        "category": "research",
        "description": "Most powerful deep research model for multi-step web research",
        "strengths": ["research", "web-search", "analysis"],
        "use_cases": ["deep-research", "fact-finding"],
        "context_window": 128000,
        "max_output_tokens": 100000,
        "reasoning_effort_levels": None,
        "pricing_unit": "per_1m_tokens",
        "pricing_notes": "Research-tier pricing; varies by task",
        "api_docs_url": _doc("o3-deep-research"),
        "api_endpoint": _CHAT,
        "atlas_role": "research",
    },
    {
        "model_id": "o4-mini-deep-research",
        "display_name": "o4 Mini Deep Research",
        "family": "research",
        "category": "research",
        "description": "Faster, more affordable deep research model",
        "strengths": ["research", "cost-effective"],
        "use_cases": ["research", "summarization"],
        "context_window": 128000,
        "max_output_tokens": 100000,
        "reasoning_effort_levels": None,
        "pricing_unit": "per_1m_tokens",
        "pricing_notes": "Research-tier pricing; lower than o3",
        "api_docs_url": _doc("o4-mini-deep-research"),
        "api_endpoint": _CHAT,
        "atlas_role": "research",
    },

    # ── Open-weight ────────────────────────────────────────────────────
    {
        "model_id": "gpt-oss-120b",
        "display_name": "GPT-OSS 120B",
        "family": "open-weight",
        "category": "general",
        "description": "Most powerful open-weight model; fits on H100",
        "strengths": ["open-weight", "self-hosted"],
        "use_cases": ["self-hosted-inference", "fine-tuning"],
        "context_window": 128000,
        "max_output_tokens": 16384,
        "reasoning_effort_levels": None,
        "pricing_input": 0.12,
        "pricing_output": 0.48,
        "pricing_unit": "per_1m_tokens",
        "pricing_notes": "Approximate; via OpenAI API",
        "api_docs_url": _doc("gpt-oss-120b"),
        "api_endpoint": _CHAT,
    },
    {
        "model_id": "gpt-oss-20b",
        "display_name": "GPT-OSS 20B",
        "family": "open-weight",
        "category": "general",
        "description": "Medium-sized open-weight model for low latency",
        "strengths": ["open-weight", "fast", "self-hosted"],
        "use_cases": ["self-hosted-inference"],
        "context_window": 128000,
        "max_output_tokens": 16384,
        "reasoning_effort_levels": None,
        "pricing_input": 0.03,
        "pricing_output": 0.12,
        "pricing_unit": "per_1m_tokens",
        "pricing_notes": "Approximate; via OpenAI API",
        "api_docs_url": _doc("gpt-oss-20b"),
        "api_endpoint": _CHAT,
    },

    # ── Reasoning (o-series) ───────────────────────────────────────────
    {
        "model_id": "o3",
        "display_name": "o3",
        "family": "o-series",
        "category": "reasoning",
        "description": "Complex task reasoning model (succeeded by GPT-5)",
        "strengths": ["reasoning", "math", "coding"],
        "use_cases": ["complex-reasoning", "math"],
        "context_window": 200000,
        "max_output_tokens": 100000,
        "reasoning_effort_levels": ["low", "medium", "high"],
        "pricing_input": 2.00,
        "pricing_cached_input": 0.50,
        "pricing_output": 8.00,
        "pricing_unit": "per_1m_tokens",
        "pricing_notes": "Post June 2025 80% price reduction",
        "api_docs_url": _doc("o3"),
        "api_endpoint": _CHAT,
        "notes": "Succeeded by GPT-5 reasoning models",
    },
    {
        "model_id": "o3-pro",
        "display_name": "o3 Pro",
        "family": "o-series",
        "category": "reasoning",
        "description": "More compute for better reasoning responses",
        "strengths": ["deep-reasoning", "precision"],
        "use_cases": ["high-stakes-reasoning"],
        "context_window": 200000,
        "max_output_tokens": 100000,
        "reasoning_effort_levels": ["low", "medium", "high"],
        "pricing_input": 20.00,
        "pricing_output": 80.00,
        "pricing_unit": "per_1m_tokens",
        "api_docs_url": _doc("o3-pro"),
        "api_endpoint": _CHAT,
    },
    {
        "model_id": "o4-mini",
        "display_name": "o4 Mini",
        "family": "o-series",
        "category": "reasoning",
        "description": "Fast, cost-efficient reasoning (succeeded by GPT-5 Mini)",
        "strengths": ["reasoning", "fast", "cost-effective"],
        "use_cases": ["reasoning", "coding"],
        "context_window": 200000,
        "max_output_tokens": 100000,
        "reasoning_effort_levels": ["low", "medium", "high"],
        "pricing_input": 1.10,
        "pricing_cached_input": 0.275,
        "pricing_output": 4.40,
        "pricing_unit": "per_1m_tokens",
        "api_docs_url": _doc("o4-mini"),
        "api_endpoint": _CHAT,
        "notes": "Succeeded by GPT-5 Mini",
    },
    {
        "model_id": "o3-mini",
        "display_name": "o3 Mini",
        "family": "o-series",
        "category": "reasoning",
        "description": "Small alternative to o3 for reasoning tasks",
        "strengths": ["reasoning", "cost-effective"],
        "use_cases": ["reasoning"],
        "context_window": 200000,
        "max_output_tokens": 100000,
        "reasoning_effort_levels": ["low", "medium", "high"],
        "pricing_input": 1.10,
        "pricing_cached_input": 0.275,
        "pricing_output": 4.40,
        "pricing_unit": "per_1m_tokens",
        "api_docs_url": _doc("o3-mini"),
        "api_endpoint": _CHAT,
    },

    # ── Computer Use / Search ──────────────────────────────────────────
    {
        "model_id": "computer-use-preview",
        "display_name": "Computer Use Preview",
        "family": "gpt-5.4",
        "category": "general",
        "description": "Specialized model for computer use tool",
        "strengths": ["computer-use", "GUI-interaction"],
        "use_cases": ["desktop-automation"],
        "context_window": 128000,
        "max_output_tokens": 16384,
        "reasoning_effort_levels": None,
        "api_docs_url": _doc("computer-use-preview"),
        "api_endpoint": _RESPONSES,
    },
    {
        "model_id": "gpt-4o-search-preview",
        "display_name": "GPT-4o Search Preview",
        "family": "gpt-4o",
        "category": "general",
        "description": "Web search integrated into Chat Completions",
        "strengths": ["web-search", "grounded-answers"],
        "use_cases": ["web-research", "fact-checking"],
        "context_window": 128000,
        "max_output_tokens": 16384,
        "reasoning_effort_levels": None,
        "pricing_input": 2.50,
        "pricing_output": 10.00,
        "pricing_unit": "per_1m_tokens",
        "pricing_notes": "Plus $10/1K web search tool calls",
        "api_docs_url": _doc("gpt-4o-search-preview"),
        "api_endpoint": _CHAT,
    },
    {
        "model_id": "gpt-4o-mini-search-preview",
        "display_name": "GPT-4o Mini Search Preview",
        "family": "gpt-4o",
        "category": "general",
        "description": "Fast, affordable web search in Chat Completions",
        "strengths": ["web-search", "cost-effective"],
        "use_cases": ["web-research"],
        "context_window": 128000,
        "max_output_tokens": 16384,
        "reasoning_effort_levels": None,
        "pricing_input": 0.15,
        "pricing_output": 0.60,
        "pricing_unit": "per_1m_tokens",
        "pricing_notes": "Plus $25/1K web search tool calls (non-reasoning preview)",
        "api_docs_url": _doc("gpt-4o-mini-search-preview"),
        "api_endpoint": _CHAT,
    },

    # ── Legacy (deprecated) ────────────────────────────────────────────
    {
        "model_id": "gpt-4o",
        "display_name": "GPT-4o",
        "family": "gpt-4o",
        "category": "general",
        "description": "Previous-gen multimodal model",
        "strengths": ["multimodal", "general-purpose"],
        "use_cases": ["general-assistant"],
        "context_window": 128000,
        "max_output_tokens": 16384,
        "reasoning_effort_levels": None,
        "pricing_input": 2.50,
        "pricing_cached_input": 1.25,
        "pricing_output": 10.00,
        "pricing_unit": "per_1m_tokens",
        "api_docs_url": _doc("gpt-4o"),
        "api_endpoint": _CHAT,
        "is_deprecated": True,
        "notes": "Succeeded by gpt-5.2",
    },
    {
        "model_id": "gpt-4o-mini",
        "display_name": "GPT-4o Mini",
        "family": "gpt-4o",
        "category": "general",
        "description": "Small, fast GPT-4o variant",
        "strengths": ["fast", "cost-effective"],
        "use_cases": ["general-assistant"],
        "context_window": 128000,
        "max_output_tokens": 16384,
        "reasoning_effort_levels": None,
        "pricing_input": 0.15,
        "pricing_cached_input": 0.075,
        "pricing_output": 0.60,
        "pricing_unit": "per_1m_tokens",
        "api_docs_url": _doc("gpt-4o-mini"),
        "api_endpoint": _CHAT,
        "is_deprecated": True,
        "notes": "Succeeded by gpt-5-mini",
    },
    {
        "model_id": "gpt-4-turbo",
        "display_name": "GPT-4 Turbo",
        "family": "legacy",
        "category": "general",
        "description": "Legacy GPT-4 Turbo model",
        "strengths": ["general-purpose"],
        "use_cases": ["general-assistant"],
        "context_window": 128000,
        "max_output_tokens": 4096,
        "reasoning_effort_levels": None,
        "pricing_input": 10.00,
        "pricing_output": 30.00,
        "pricing_unit": "per_1m_tokens",
        "api_docs_url": _doc("gpt-4-turbo"),
        "api_endpoint": _CHAT,
        "is_deprecated": True,
    },
    {
        "model_id": "gpt-4",
        "display_name": "GPT-4",
        "family": "legacy",
        "category": "general",
        "description": "Original GPT-4 model",
        "strengths": ["general-purpose"],
        "use_cases": ["general-assistant"],
        "context_window": 8192,
        "max_output_tokens": 4096,
        "reasoning_effort_levels": None,
        "pricing_input": 30.00,
        "pricing_output": 60.00,
        "pricing_unit": "per_1m_tokens",
        "api_docs_url": _doc("gpt-4"),
        "api_endpoint": _CHAT,
        "is_deprecated": True,
    },
    {
        "model_id": "gpt-3.5-turbo",
        "display_name": "GPT-3.5 Turbo",
        "family": "legacy",
        "category": "general",
        "description": "Legacy fast, cheap model",
        "strengths": ["fast", "cheap"],
        "use_cases": ["simple-tasks"],
        "context_window": 16384,
        "max_output_tokens": 4096,
        "reasoning_effort_levels": None,
        "pricing_input": 0.50,
        "pricing_output": 1.50,
        "pricing_unit": "per_1m_tokens",
        "api_docs_url": _doc("gpt-3.5-turbo"),
        "api_endpoint": _CHAT,
        "is_deprecated": True,
    },
    {
        "model_id": "dall-e-3",
        "display_name": "DALL-E 3",
        "family": "legacy",
        "category": "image",
        "description": "Previous-gen image generation model",
        "strengths": ["image-generation"],
        "use_cases": ["image-creation"],
        "context_window": None,
        "max_output_tokens": None,
        "reasoning_effort_levels": None,
        "pricing_unit": "per_image",
        "pricing_notes": "Standard 1024x1024: $0.04; HD: $0.08-$0.12",
        "api_docs_url": _doc("dall-e-3"),
        "api_endpoint": _IMG,
        "is_deprecated": True,
        "notes": "Succeeded by gpt-image-1",
    },
    {
        "model_id": "dall-e-2",
        "display_name": "DALL-E 2",
        "family": "legacy",
        "category": "image",
        "description": "Legacy image generation model",
        "strengths": ["image-generation"],
        "use_cases": ["image-creation"],
        "context_window": None,
        "max_output_tokens": None,
        "reasoning_effort_levels": None,
        "pricing_unit": "per_image",
        "pricing_notes": "Standard 1024x1024: $0.02",
        "api_docs_url": _doc("dall-e-2"),
        "api_endpoint": _IMG,
        "is_deprecated": True,
    },
    {
        "model_id": "o1",
        "display_name": "o1",
        "family": "o-series",
        "category": "reasoning",
        "description": "First-gen reasoning model",
        "strengths": ["reasoning"],
        "use_cases": ["reasoning"],
        "context_window": 200000,
        "max_output_tokens": 100000,
        "reasoning_effort_levels": ["low", "medium", "high"],
        "pricing_input": 15.00,
        "pricing_output": 60.00,
        "pricing_unit": "per_1m_tokens",
        "api_docs_url": _doc("o1"),
        "api_endpoint": _CHAT,
        "is_deprecated": True,
        "notes": "Succeeded by o3",
    },
    {
        "model_id": "o1-pro",
        "display_name": "o1 Pro",
        "family": "o-series",
        "category": "reasoning",
        "description": "First-gen pro reasoning model",
        "strengths": ["deep-reasoning"],
        "use_cases": ["high-stakes-reasoning"],
        "context_window": 200000,
        "max_output_tokens": 100000,
        "reasoning_effort_levels": ["low", "medium", "high"],
        "pricing_input": 150.00,
        "pricing_output": 600.00,
        "pricing_unit": "per_1m_tokens",
        "api_docs_url": _doc("o1-pro"),
        "api_endpoint": _CHAT,
        "is_deprecated": True,
        "notes": "Succeeded by o3-pro",
    },
    {
        "model_id": "o1-mini",
        "display_name": "o1 Mini",
        "family": "o-series",
        "category": "reasoning",
        "description": "First-gen mini reasoning model",
        "strengths": ["reasoning", "cost-effective"],
        "use_cases": ["reasoning"],
        "context_window": 128000,
        "max_output_tokens": 65536,
        "reasoning_effort_levels": ["low", "medium", "high"],
        "pricing_input": 1.10,
        "pricing_output": 4.40,
        "pricing_unit": "per_1m_tokens",
        "api_docs_url": _doc("o1-mini"),
        "api_endpoint": _CHAT,
        "is_deprecated": True,
        "notes": "Succeeded by o4-mini",
    },
    {
        "model_id": "babbage-002",
        "display_name": "Babbage 002",
        "family": "legacy",
        "category": "general",
        "description": "Legacy base model for fine-tuning",
        "strengths": ["fine-tuning"],
        "use_cases": ["fine-tuning"],
        "context_window": 16384,
        "max_output_tokens": 4096,
        "reasoning_effort_levels": None,
        "pricing_input": 0.40,
        "pricing_output": 0.40,
        "pricing_unit": "per_1m_tokens",
        "api_docs_url": _doc("babbage-002"),
        "api_endpoint": _CHAT,
        "is_deprecated": True,
    },
    {
        "model_id": "davinci-002",
        "display_name": "Davinci 002",
        "family": "legacy",
        "category": "general",
        "description": "Legacy base model for fine-tuning",
        "strengths": ["fine-tuning"],
        "use_cases": ["fine-tuning"],
        "context_window": 16384,
        "max_output_tokens": 4096,
        "reasoning_effort_levels": None,
        "pricing_input": 2.00,
        "pricing_output": 2.00,
        "pricing_unit": "per_1m_tokens",
        "api_docs_url": _doc("davinci-002"),
        "api_endpoint": _CHAT,
        "is_deprecated": True,
    },
]
